### ISSUE TITLE
Unknown type errors when bilding in XCode 7.2

### ISSUE THREAD

**Issue by chuckmitchell** [tomball/j2objc-sample-reversi#5]
I cloned this project and configured J2OBJC_HOME to point to the latest j2objc (0.9.8.2.1).

I head to change the Header search path in xcode to "${J2OBJC_HOME}/include" since ${J2OBJC_HOME}/frameworks/JRE.framework/Headers" does not exist in j2obj-dist anymore.
I was missing header files when building.

I no longer get missing header files error but I do get lots of unknown type errors.
Is this something to do with LLVM changing, or is it a setup step I'm missing? Either way the build instructions need to change. It's probably something small.

/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_types.h
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_types.h:28:9: Unknown type name 'uint16_t'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_types.h:36:9: Unknown type name 'bool'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:65:1: Unknown type name 'CF_EXTERN_C_BEGIN'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:67:1: Expected identifier or '('
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:78:50: Unknown type name 'NS_RELEASES_ARGUMENT'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:78:74: Expected ')'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:81:58: Unknown type name 'NS_RELEASES_ARGUMENT'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:81:82: Expected ')'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:86:1: Unknown type name 'NSString'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:88:1: Unknown type name 'CF_EXTERN_C_END'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:92:1: Expected identifier or '('
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/J2ObjC_common.h:108:33: No known instance method for selector 'isKindOfClass:'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h:33:12: Cannot find interface declaration for 'NSObject'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h:54:58: Unknown type name 'NSObject'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h:55:32: Unknown type name 'NS_RETURNS_RETAINED'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h:55:52: Expected identifier or '('
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h:60:37: Cannot find interface declaration for 'NSObject', superclass of 'JreObjectCategoryDummy'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h:65:1: Unknown type name 'FOUNDATION_EXPORT'
/Users/charles/j2objcDist/j2objc-0.9.8.2.1/include/NSObject+JavaObject.h:65:1: Expected ';' after top level declarator
Too many errors emitted, stopping now

**Comment by tomball** [comment]
It looks like the Xcode's command-line tools are not installed on your system, since that's where symbols like uint16_t and CF_EXTERN_C_BEGIN are defined. Here's a StackOverflow question that may help:

http://stackoverflow.com/questions/32893412/command-line-tools-not-working-os-x-el-capitan

**Comment by chuckmitchell** [comment]
Hi Tom
Thank you for the suggestion. 

```
$xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

I built the frameworks, updated Settings.xcconfig and tried again but I'm still getting identical errors.
Any other suggestions?

Charles

**Comment by tomball** [comment]
Can you attach a log file, or cut&paste what Xcode shows you? I'm especially interested in environment variables, but also the full command-line that is failing.

**Comment by ajitam** [comment]
I also noticed that Settings.xcconfig is pointing to unknown destination
```
HEADER_SEARCH_PATHS = "${J2OBJC_HOME}/frameworks/JRE.framework/Headers";
FRAMEWORK_SEARCH_PATHS = "${J2OBJC_HOME}/frameworks";
```

any comment on that? where can I find JRE.framework?

**Comment by tomball** [comment]
Either download [the latest j2objc release](https://github.com/google/j2objc/releases/tag/1.0.1), or build the latest source with "make frameworks" or "make all_dist".
