### ISSUE TITLE
errors while including JRE.framework

### ISSUE THREAD

**Issue by wedkarz** [tomball/j2objc-sample-reversi#6]
HEADER_SEARCH_PATHS asks for framework that doesn't exist: HEADER_SEARCH_PATHS = "${J2OBJC_HOME}/frameworks/JRE.framework/Headers"

which I managed to fix as HEADER_SEARCH_PATHS = "${J2OBJC_HOME}/include"

but still there is framework needed: FRAMEWORK_SEARCH_PATHS = "${J2OBJC_HOME}/frameworks";

**Comment by tomball** [comment]
Either build the j2objc base with "make frameworks", or use [the latest j2objc release](https://github.com/google/j2objc/releases/tag/1.0.1):

```bash
$ unzip -l /Users/tball/Downloads/j2objc-1.0.1.zip |grep frameworks/JRE.framework/Headers
       24  02-09-16 10:04   j2objc-1.0.1/frameworks/JRE.framework/Headers
```

Once you have the frameworks and the framework search path set, there's no need to change the HEADER_SEARCH_PATHS.

**Comment by wedkarz** [comment]
Great, thanks. The reason of this my confusion was doc in here: http://j2objc.org/docs/Building-J2ObjC.html

Is it valid to use somehow j2objc without building frameworks? If not, maybe it can be added in this doc to help confused people, who are new to approach? I would appreciate it.

Thanks for assistance!

**Comment by tomball** [comment]
I just updated the build doc -- thanks for letting us know it was out of date.
