### ISSUE TITLE
[Question] Manually adding java sources to compile sources

### ISSUE THREAD

**Issue by wedkarz** [tomball/j2objc-sample-reversi#7]
Is there any way to avoid manually adding java files to "compile sources" section in build phases of xcode project?

I would like to have subrepository in git, that would contain common (engine) files for couple projects.

**Comment by tomball** [comment]
You can use Gradle or Make to build your library, then use an External Build target that your app depends upon. That's how j2objc's JreEmulation Xcode project is set up.

In the future, another option is Bazel, an open-source version of the build system Google uses internally. It supports wildcarding source files in build rules, and its Objective C rules generate new Xcode projects automatically. However, its j2objc support is still being developed.

The alternative is to get a job at Apple and fix Xcode to be more supportive of large projects. ;-)

**Comment by tomball** [comment]
I updated the previous comment with links to its topics.
