### ISSUE TITLE
Update Project for j2objc 2.x

### ISSUE THREAD

**Issue by sghiassy** [tomball/j2objc-sample-reversi#8]
Seems like this project no longer compiles with the new 2.x version of j2objc.

**Comment by tomball** [comment]
Added iconv library dependency, updated project settings to Xcode 9's recommendation.

The app doesn't run any more, though, as its UI was always poor and now click XY positions are off. I'm not an iOS developer, but someone who is can probably fix it quickly. Pull requests cheerfully accepted!

**Comment by sghiassy** [comment]
Can you post how you added the `iconv` library dependency? Is that part of the j2objc library?

**Comment by tomball** [comment]
Already done: [Required Link Flags](https://developers.google.com/j2objc/guides/required-link-flags) 🙂

**Comment by tomball** [comment]
To add an external library dependency in Xcode (true for all iOS apps, nothing specific about j2objc), select the target, then its Build Phases section, then expand the Link Binary With Libraries section, and click the + button below the list.
